Repository FOE-Tools/FOE-Tools.github.io, pull requests merged in 2020-11, with the labels that each got.

#358 Add Vercel sponsor
  .circleci/config.yml
  README.md
  assets/style.scss
  assets/theme/light/theme.scss
  lang/de.json
  lang/hu.json
  lang/it.json
  lang/nl.json
  lang/pl.json
  lang/pt.json
  lang/sk.json
  lang/sv.json
  lang/tr.json
  layouts/_default/template.pug
  nuxt.config.js
  package-lock.json
  package.json
  pages/survey/script.js
  static/vercel-dark.svg
  static/vercel-light.svg
  store/index.js
  yarn.lock
Labels: enhancement

#361 Split "Default" layout and hide top menu on scroll
  assets/style.scss
  components/main-footer/MainFooter.vue
  components/main-footer/script.js
  components/main-footer/template.pug
  components/main-header/MainHeader.vue
  components/main-header/components/dialogDayNight/DialogDayNight.vue
  components/main-header/components/dialogDayNight/script.js
  components/main-header/components/dialogDayNight/template.pug
  components/main-header/components/dialogGlobalSettings/DialogGlobalSettings.vue
  components/main-header/components/dialogGlobalSettings/script.js
  components/main-header/components/dialogGlobalSettings/template.pug
  components/main-header/script.js
  components/main-header/template.pug
  jest.config.js
  layouts/_default/script.js
  layouts/_default/template.pug
  nuxt.config.js
  pages/survey/script.js
  plugins/moment.js
  plugins/nuxtClientInit.js
  store/index.js
  test/unit/__snapshots__/layouts.test.js.snap
  test/unit/components/main-header.js
  test/unit/layouts/default.js
  test/unit/localVue.js
Labels: enhancement, refactoring

#363 Multiple features added
  components/gb-investment/script.js
  components/gb-investment/template.pug
  components/gb-list-select/script.js
  components/gb-list-select/template.pug
  components/main-header/components/dialogGlobalSettings/script.js
  components/show-bookmarks/ShowBookmarks.vue
  components/show-bookmarks/script.js
  components/show-bookmarks/template.pug
  lang/en.json
  lang/fi.json
  lang/fr.json
  lang/ru.json
  pages/gb-investment/script.js
  pages/gb-investment/template.pug
  pages/home/script.js
  pages/home/template.pug
  plugins/fontawesome.js
  plugins/nuxtClientInit.js
  scripts/utils.js
  store/global.js
  store/profile.js
  test/unit/components/gb-list-select.js
  test/unit/utils.js
  translations/common.json
  translations/en.po
  translations/fr.po
Labels: enhancement

#366 Fix issue related to day/night system mode on old devices
  plugins/nuxtClientInit.js
Labels: bug

#371 Updated NavBar style
  assets/style.scss
Labels: ui

#373 Fix multi-tabs sync
  package-lock.json
  package.json
  plugins/vuex-persist.js
  yarn.lock
Labels: bug

#375 Small UI fixes
  components/main-header/template.pug
  pages/contributors/template.pug
Labels: bug, ui

#377 GB Investment: add buttons to automatically add owner/investor correct amount
  components/gb-investment/script.js
  components/gb-investment/template.pug
  components/main-header/script.js
  components/main-header/template.pug
  plugins/fontawesome.js
Labels: enhancement

#390 Do some changes related to incomplete translations
  assets/theme/dark/theme.scss
  components/language-selector/template.pug
  components/main-header/template.pug
  lang/de.json
  lang/en.json
  lang/es.json
  lang/fr.json
  lang/ru.json
  layouts/_default/script.js
  pages/help-to-translate-the-site/script.js
  pages/help-to-translate-the-site/template.pug
  plugins/nuxtClientInit.js
  store/global.js
  store/index.js
  translations/common.json
  translations/en.po
  translations/fr.po
Labels: enhancement, ui

#394 Moving from Matomo to Plausible Analytics
  app.html
  lang/de.json
  lang/en.json
  lang/es.json
  lang/fr.json
  lang/ru.json
  lang/sk.json
  lang/sv.json
  lib/vuex-pathify/build/rollup.js
  lib/vuex-pathify/package-lock.json
  lib/vuex-pathify/package.json
  pages/cookie-policy/script.js
  pages/privacy-policy/script.js
  pages/privacy-policy/template.pug
  plugins/cookieConsent.js
  translations/en.po
  translations/fr.po
  translations/sk.po
  translations/sv.po
Labels: enhancement

#395 Fix issue related to obtaining the status of the translation
  plugins/nuxtClientInit.js
Labels: bug
